version: "3.4"
services:
  postgres:
    image: "postgres:alpine"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sujanm@9271
  weaviate:

    image: semitechnologies/weaviate:1.21.2
    command:
      - --host
      - 0.0.0.0
      - --port
      - "5432"
      - --scheme
      - http
    ports:
      - 5435:5432
    volumes:
      - ./data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      # While these are the default enabled modules from the Weaviate docs,
      # we won't be using these but instead our custom embedding model, GTE-base
      ENABLE_MODULES: "text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai"
      CLUSTER_HOSTNAME: "node1"
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    depends_on:
      - weaviate
      - postgres
networks:
  app_network:
    driver: bridge
